FORMAT: 1A
HOST: https://rcrcsims.org/api

# SIMS Portal

Surge Information Management Support (SIMS) is a global network of Information Management specialists who support IFRC emergency response operations by providing a variety of services and products. Key areas of technical support include geospatial analysis, web-based and static data visualization, mobile data collection, scenario planning, and much more.

## Users [/users]

### Get All Users [GET]

+ Response 200 (application/json)

        [
          {
            "admin": true,
            "email": "jonathan.garro@redcross.org",
            "first_name": "Jonathan",
            "id": 1,
            "last_name": "Garro",
            "location": "Washington, DC, USA",
            "ns_id": 4,
            "slack": "UDU4ZRLGY",
            "status": "Active",
            "time_zone": "America/New_York",
            "title": "Data Engineering Lead"
          }
         ]