FORMAT: 1A
HOST: https://rcrcsims.org/api

# SIMS Portal

Surge Information Management Support (SIMS) is a global network of Information Management specialists who support IFRC emergency response operations by providing a variety of services and products. Key areas of technical support include geospatial analysis, web-based and static data visualization, mobile data collection, scenario planning, and much more.

## Users [/users{?status}]

### Get Users [GET]

`Active` and `Inactive` (but not `Pending`) member data is returned. Available attributes include: 

- `admin`: Boolean
- `email`: String
- `first_name` and `last_name`: String
- `location`: String
- `slack`: String
- `status`: String
- `ns_id`: Integer
- `time_zone`: String
- `title`: String

+ Parameters
    + status (string, optional) - Set to `Active` or `Inactive`

+ Response 200 (application/json)
    ```
    [
        {
            "admin": true,
            "email": "jonathan.garro@redcross.org",
            "first_name": "Jonathan",
            "id": 1,
            "last_name": "Garro",
            "location": "Washington, DC, USA",
            "ns_id": 4,
            "slack": "UDU4ZRLGY",
            "status": "Active",
            "time_zone": "America/New_York",
            "title": "Data Engineering Lead"
        }
    ]
    ```


## Portfolio [/portfolio{?emergency_id}]

### Get Approved Products by Emergency [GET]

Approved products are those that have been verified for external sharing by a SIMS Remote Coordinator for that emergency. This endpoint requires the `emergency_id`, which corresponds to the relevant emergency page in the [IFRC GO Platform](go.ifrc.org). Available attributes include:

- `title`: String
- `type`: String
- `description`: String
- `image_file`: String

+ Parameters
    + emergency_id (integer, required) - The GO Platform emergency ID
    
+ Response 200 (application/json)
    ```
    [
        {
            "description": "A map showing the direction of refugees and returnees fleeing the Sudan Crisis. The field needed a representation of the overall trend of movement across the border, as well as where people were congregating. This was produced as part of a suite of PMER outputs for usage in the Operational Strategy, Emergency Appeal, and more.",
            "image_file": "portfolio_cover_images/Map-user17-cb80965e096f0bec.png",
            "title": "Chad Displacement Map",
            "type": "Map"
        }
    ]
    ```
    
## Emergencies [/emergencies{?status,emergency_id,iso3}]

### Get Emergencies [GET]

SIMS only maintains records of emergencies for which the network has been activated. The endpoint accepts three optional parameters: `status` with **Active** or **Closed**; `emergency_id`, which corresponds to the relevant emergency page in the [IFRC GO Platform](go.ifrc.org); and `iso3`, which accepts a three-letter code of the country primarily affected by the emergency. Available attributes include:

- `emergency_name`: String
- `country_name`: String
- `emergency_type`: Strin
- `iso3`: String
- `status`: String
- `activation_details`: String
- `go_emergency_id`: Integer
- `slack_channel`: String

+ Parameters
    + status (string, optional) - Set to `Active` or `Closed`
    + emergency_id (integer, optional) - The GO Platform emergency ID
    + iso3 (string, optional) - The three-letter iso3 code of the primary country

+ Response 200 (application/json)
    ```
    [
        {
            "emergency_name": "Bangladesh Floods"
            "activation_details": "In August 2017, heavy monsoon rains above the seasonal average severely impacted the riverine region of India, Nepal,
Bhutan and Bangladesh which resulted in intense flooding in almost two- thirds of Bangladesh. According to the National
Disaster Response Coordination Centre (NDRCC) report on 20 August 2017, around 6.9 million people were affected,
approximately 593,247 houses and 650,000 hectares crops were damaged. The death toll reported was 114 people and
297,254 people were displaced.",
            "country_name": "Bangladesh",
            "emergency_type": "Floods",
            "go_emergency_id": 14,
            "iso3": "BGD",
            "slack_channel": "C05DS1VKULW",
            "status": "Active"
        }
    ]
    ```