services:
  web:
    build: .
    volumes: 
      - ./SIMS_Portal:/app/SIMS_Portal
      - ./db:/app/db
      - ./migrations:/app/migrations
    ports:
      - "5001:5000"
    env_file: ./.env
    depends_on:
      - postgresdb
      
  postgresdb:
    image: postgres:13.5-alpine
    restart: always
    environment:
      - POSTGRES_USER=simsportal
      - POSTGRES_PASSWORD=simsportal
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local