services:
  web:
    build: .
    volumes: 
      - ./SIMS_Portal:/app/SIMS_Portal
      - ./db:/app/db
      - ./migrations:/app/migrations
    ports:
      - "5001:5000"
    env_file: ./.env
    depends_on:
      - postgresdb
    command: gunicorn --bind 0.0.0.0:5000 -w 3 run:app

  postgresdb:
    image: postgres:13.5-alpine
    restart: always
    environment:
      - POSTGRES_USER=simsportal
      - POSTGRES_PASSWORD=simsportal
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
  
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  db:
    driver: local
