services:
  web:
    build: .
    volumes: 
      - ./SIMS_Portal:/app/SIMS_Portal
      - ./db:/app/db
      - ./migrations:/app/migrations
    ports:
      - "5001:5000"
    env_file: ./.env
    # command: gunicorn --bind 0.0.0.0:5000 -w 3 --preload run:app