"""remove wp_id

Revision ID: 1f05ced78d0d
Revises: 7dc906782336
Create Date: 2023-10-10 15:22:34.150530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f05ced78d0d'
down_revision = '7dc906782336'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documentation', 'wp_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documentation', sa.Column('wp_id', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
