"""empty message

Revision ID: 6391611b1aab
Revises: eb7e505c011d
Create Date: 2023-06-22 20:15:26.992181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6391611b1aab'
down_revision = 'eb7e505c011d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('availability', sa.Column('timeframe', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('availability', 'timeframe')
    # ### end Alembic commands ###
