"""add featured to documentation

Revision ID: 7ac710d189fc
Revises: 9e06804d4b51
Create Date: 2023-10-10 08:33:52.684399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ac710d189fc'
down_revision = '9e06804d4b51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documentation', sa.Column('featured', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documentation', 'featured')
    # ### end Alembic commands ###
