"""remove constraint on portfolio_id

Revision ID: 7dc906782336
Revises: 7ac710d189fc
Create Date: 2023-10-10 09:23:41.789236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7dc906782336'
down_revision = '7ac710d189fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documentation', 'portfolio_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documentation', 'portfolio_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
