"""empty message

Revision ID: 80d10eef84db
Revises: d5b5645b6230
Create Date: 2023-06-23 23:14:16.361806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80d10eef84db'
down_revision = 'd5b5645b6230'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('availability', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('availability', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('availability', 'updated_at')
    op.drop_column('availability', 'created_at')
    # ### end Alembic commands ###
