"""add summary to documentation

Revision ID: 8eca597ab324
Revises: f322bde30174
Create Date: 2023-10-09 16:41:06.069351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8eca597ab324'
down_revision = 'f322bde30174'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documentation', sa.Column('summary', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documentation', 'summary')
    # ### end Alembic commands ###
