"""add portfolio_id linkage

Revision ID: 9e06804d4b51
Revises: 8eca597ab324
Create Date: 2023-10-09 19:04:36.586650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e06804d4b51'
down_revision = '8eca597ab324'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documentation', sa.Column('portfolio_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'documentation', 'portfolio', ['portfolio_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'documentation', type_='foreignkey')
    op.drop_column('documentation', 'portfolio_id')
    # ### end Alembic commands ###
