"""Add task_completed_by to AssignmentSubTask and fix table relationships

Revision ID: c02b8677c08a
Revises: d72668cace33
Create Date: 2025-09-13 16:10:53.813741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c02b8677c08a'
down_revision = 'd72668cace33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignment_sub_task', sa.Column('task_completed_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'assignment_sub_task', 'user', ['task_completed_by'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'assignment_sub_task', type_='foreignkey')
    op.drop_column('assignment_sub_task', 'task_completed_by')
    # ### end Alembic commands ###
