"""empty message

Revision ID: c0f52bcd2a84
Revises: 80d10eef84db
Create Date: 2023-06-25 15:41:01.938593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0f52bcd2a84'
down_revision = '80d10eef84db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('assignment', 'start_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('assignment', 'end_date',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('assignment', 'end_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('assignment', 'start_date',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###
