"""empty message

Revision ID: d5b5645b6230
Revises: 6391611b1aab
Create Date: 2023-06-23 18:36:04.923266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5b5645b6230'
down_revision = '6391611b1aab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assignment', sa.Column('hours', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assignment', 'hours')
    # ### end Alembic commands ###
