"""Added sub-task tables

Revision ID: d72668cace33
Revises: d2127d725972
Create Date: 2025-07-13 17:45:06.505920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd72668cace33'
down_revision = 'd2127d725972'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sub_task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('checklist_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('task_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['checklist_id'], ['checklist.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assignment_sub_task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assignment_checklist_id', sa.Integer(), nullable=False),
    sa.Column('sub_task_id', sa.Integer(), nullable=False),
    sa.Column('task_completed', sa.Boolean(), nullable=True),
    sa.Column('task_completed_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assignment_checklist_id'], ['assignment_checklist.id'], ),
    sa.ForeignKeyConstraint(['sub_task_id'], ['sub_task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('assignment_sub_task')
    op.drop_table('sub_task')
    # ### end Alembic commands ###
